apiVersion: v2
name: generic-app
description: Wrapper chart to deploy <app-name> via the shared generic-app chart
type: application
version: 0.1.0

dependencies:
  - name: generic-app
    version: "0.2.2"
    repository: "oci://ghcr.io/cmoreira-dev/charts"