apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teupadel-ui
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: teupadel-ui=344965637185.dkr.ecr.us-east-1.amazonaws.com/teupadel/ui
    argocd-image-updater.argoproj.io/teupadel-ui.update-strategy: newest-build
    argocd-image-updater.argoproj.io/teupadel-ui.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/teupadel-ui.helm.image-tag: generic-app.image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:helm/ui/values.yaml
spec:
  project: homelab
  source:
    repoURL: https://github.com/cmoreira-dev/gitops.teupadel.com.git
    targetRevision: main
    path: helm/ui
  destination:
    server: https://kubernetes.default.svc
    namespace: teupadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true